{
 "title": "Docker Nodes Monitor",
 "description": "Nodes And Stacks metrics",
 "tags": [ "swarmprom" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "stack",
    "label": "Stack",
    "query": "query_result(count(container_last_seen{container_label_com_docker_stack_namespace =~\".+\"}) by (container_label_com_docker_stack_namespace))"
   },
   { "name": "node_name", "label": "Nodes", "query": "node_meta" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "topk(1, sum((node_time_seconds - node_boot_time_seconds) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"}) by (node_name))"
    }
   ]
  },
  {
   "title": "Stacks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_stack_namespace=~\".+\"}) by (container_label_com_docker_stack_namespace))"
    }
   ]
  },
  {
   "title": "Stack Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(time() - min(container_start_time_seconds{container_label_com_docker_stack_namespace=~\"$stack\"}))"
    }
   ]
  },
  {
   "title": "Stack Services",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_stack_namespace=~\"$stack\"}) by (container_label_com_docker_swarm_service_name))"
    }
   ]
  },
  {
   "title": "Stack Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{container_label_com_docker_stack_namespace=~\"$stack\"}[5m])) "
    }
   ]
  },
  {
   "title": "Available Swap Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_SwapFree_bytes * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_swarm_node_id =~\".+\"}) by (container_label_com_docker_swarm_node_id))"
    }
   ]
  },
  {
   "title": "Current Node Services",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_stack_namespace=~\"$stack\", hostname=~\"$node_name\"}) by (container_label_com_docker_swarm_service_name))"
    }
   ]
  },
  {
   "title": "Current Node Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_stack_namespace=~\"$stack\", hostname=~\"$node_name\"}) by (container_label_com_docker_swarm_service_name))"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum((node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"} * 100) / count(node_meta * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{device=~\"^/dev/.*$\"} * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"} )/ sum(node_filesystem_size_bytes{device=~\"^/dev/.*$\"} * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"}) * 100"
    }
   ]
  },
  {
   "title": "Available CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\"}[$interval]) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"}) * 100 / count(node_cpu_seconds_total{mode=\"user\"} * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"}) "
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "Total Disk  Space",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{device=~\"^/dev/.*$\"} * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum((node_filesystem_size_bytes{device=~\"^/dev/.*$\"} - node_filesystem_free_bytes{device=~\"^/dev/.*$\"}) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "Total CPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\"} * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate (node_cpu_seconds_total{mode!=\"idle\"}[$interval]) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "System Load by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5 * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"}",
     "legendFormat": "load5 {{node_name}}-{{host_ip}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[$interval])  * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"} * 100)by (node_name,host_ip))",
     "legendFormat": "{{node_name}}-{{host_ip}}"
    }
   ]
  },
  {
   "title": "Memory usage by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes - node_memory_Buffers_bytes - node_memory_Slab_bytes) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"}) by (node_name,host_ip)",
     "legendFormat": "Used {{node_name}}-{{host_ip}}"
    },
    {
     "expr": "sum(node_memory_Cached_bytes * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"}) by (node_name,host_ip)",
     "legendFormat": "Cached {{node_name}}-{{host_ip}}"
    }
   ]
  },
  {
   "title": "Disk I/O by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[$interval]) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"}) by (node_name,host_ip)",
     "legendFormat": "Read {{node_name}}-{{host_ip}}"
    },
    {
     "expr": "- sum(irate(node_disk_written_bytes_total[$interval]) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"}) by (node_name,host_ip)",
     "legendFormat": "Written {{node_name}}-{{host_ip}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_reads_completed_total[$interval]) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"}) by (node_name,host_ip)",
     "legendFormat": "Reads {{node_name}}-{{host_ip}}"
    },
    {
     "expr": "- sum(irate(node_disk_writes_completed_total[$interval]) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"}) by (node_name,host_ip)",
     "legendFormat": "Writes {{node_name}}-{{host_ip}}"
    }
   ]
  },
  {
   "title": "CPU IO Wait by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg(irate(node_cpu_seconds_total{mode=\"iowait\"}[$interval])  * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"} * 100) by (node_name,host_ip))",
     "legendFormat": "{{node_name}}-{{host_ip}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device!=\"lo\"}[$interval]) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"}) by (node_name,host_ip)",
     "legendFormat": "In: {{ device }}- {{node_name}}-{{host_ip}}"
    },
    {
     "expr": "- sum(irate(node_network_transmit_bytes_total{device!=\"lo\"}[$interval]) * on(instance) group_left(node_name) node_meta{node_name=~\"$node_name\"}) by (node_name,host_ip)",
     "legendFormat": "Out: {{ device }}- {{node_name}}-{{host_ip}}"
    }
   ]
  },
  {
   "title": "Containers Network Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{id=~\"/docker/.+\", interface=~\"^eth.+\"}[$interval]) * on(container_label_com_docker_swarm_node_id) group_left(node_name) node_meta{node_name=~\"${node_name}\"}) by (node_name,host_ip)",
     "legendFormat": "IN {{node_name}}-{{host_ip}}"
    },
    {
     "expr": "- sum(irate(container_network_transmit_bytes_total{id=~\"/docker/.+\", interface=~\"^eth.+\"}[$interval]) * on(container_label_com_docker_swarm_node_id) group_left(node_name) node_meta{node_name=~\"${node_name}\"}) by (node_name,host_ip)",
     "legendFormat": "OUT {{node_name}}-{{host_ip}}"
    }
   ]
  },
  {
   "title": "Storage Usage per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{container_label_com_docker_stack_namespace=~\"$stack\",image!=\"\",hostname=~\"$node_name\"}) by (hostname, host_ip,container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{hostname}}-{{ host_ip}} - {{ container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{container_label_com_docker_stack_namespace=~\"$stack\",image!=\"\",hostname=~\"$node_name\"}) by (hostname, host_ip,container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{hostname}}-{{host_ip}}-{{ container_label_com_docker_swarm_service_name }} "
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_label_com_docker_stack_namespace=~\"$stack\",image!=\"\",hostname=~\"$node_name\"}[$interval])) by (hostname, host_ip,container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{hostname}}-{{host_ip}}-{{ container_label_com_docker_swarm_service_name }} "
    }
   ]
  },
  {
   "title": "Incoming Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{container_label_com_docker_stack_namespace=~\"$stack\",image!=\"\",hostname=~\"$node_name\"}[$interval])) by (hostname, host_ip,container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{hostname}}-{{host_ip}}-{{ container_label_com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "Outgoing Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{container_label_com_docker_stack_namespace=~\"$stack\",image!=\"\",hostname=~\"$node_name\"}[$interval])) by (hostname, host_ip,container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{hostname}}-{{host_ip}}-{{ container_label_com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "Storage Usage per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{container_label_com_docker_stack_namespace=~\"$stack\",image!=\"\",hostname=~\"$node_name\"}) by (hostname, host_ip,container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{hostname}}-{{host_ip}}-{{ container_label_com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "Cluster members",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum(node_meta) by (node_name, host_ip, instance,node_id)"
    }
   ]
  }
 ]
}